routes/admin.php
<?php
Route::namespace('Admin')->name('admin.')->group(function () {
//General
    Route::get('home', 'SettingController@home')->name('home.index');
    Route::get('agency', 'SettingController@agency')->name('agency.index');
    Route::post('store', 'SettingController@store')->name('setting.store');
    Route::get('contact', 'SettingController@contact')->name('contact.index');
//Category
    Route::resource('category', 'CategoryController');
//Message
    Route::resource('message', 'MessageController');
//Gallery
    Route::post('gallery/order', 'GalleryController@order');
    Route::post('gallery/{project}/store', 'GalleryController@store')->name('gallery.store');
    Route::get('gallery/{project}/create', 'GalleryController@create')->name('gallery.create');
    Route::delete('gallery/{id}/delete', 'GalleryController@destroy')->name('gallery.destroy');
//Project
    Route::resource('project', 'ProjectController');
//Client
    Route::post('client/order-client', 'ClientController@order');
    Route::resource('client', 'ClientController');
//Logs
    //Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

//Auth
/*Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});*/
Auth::routes();

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', function (){
    return redirect()->route('login');
});


Route::namespace('Web')->group(function (){
    Route::get('gracias', 'HomeController@thanks')->name('thanks');
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('nosotros', 'HomeController@agency')->name('us');
    Route::get('contacto', 'HomeController@contact')->name('contact');
    Route::get('portafolio/{slug?}', 'HomeController@project')->name('portfolio');
    Route::get('/{slug}', 'HomeController@detail')->name('portfolio-detail');
    Route::post('save-contact', 'HomeController@saveContact')->name('save-contact');
});
Route::view('/404', 'errors.404');
Route::view('/500', 'errors.500');
Route::view('/503', 'errors.503');

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    const IMAGE = 'image';
    const VIDEO = 'video';

    public function getPathImage($width, $height, $format = 'png')
    {
        return isset($this->image) ?
            (strpos($this->image, 'http') !== false ?
                $this->image : config('services.whiz.images.path') . '/' . $this->image . '/' . $format . '/' . $width . '/' . $height ) : null;
    }

    public function getPathVideoAttribute()
    {
        return str_replace('watch?v=', 'embed/', $this->name);
    }
}

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Gallery;
use App\Project;
use App\Services\API\ApiWhiz;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class GalleryController extends Controller
{
    protected  $apiWhiz;
    public function __construct(ApiWhiz $apiWhiz)
    {
        $this->apiWhiz = $apiWhiz;
    }

    public function create(Project $project)
    {
        $galleries = $project->gallery()->orderBy('order', 'asc')->get();
        return view('admin.modules.gallery.index', compact('project', 'galleries'));
    }

    public function store(Request $request, Project $project)
    {
        try{
            DB::beginTransaction();
            $gallery = new Gallery();
            $gallery->order = Gallery::where('project_id', $project->id)->count() + 1;
            $gallery->project_id = $project->id;

            if($request->has('gallery') && $request->type == Gallery::IMAGE){
                $gallery->type = Gallery::IMAGE;
                $gallery->name = $request->file('gallery')->getClientOriginalName();
                $gallery->save();
                $multipart[] = ['name' => 'image[]', 'contents' => fopen($request->file('gallery')->getRealPath(), 'r')];
                $dataImage = ['table_name' => 'galleries', 'table_key' => $gallery->id];
                $responseImage = $this->apiWhiz->storeImage($dataImage, $multipart);
                if ($responseImage->response->status) {
                    $path = $responseImage->response->data[0]->uuid ?? null;
                    $gallery->image = $path;
                    $gallery->save();
                    DB::commit();
                }
                return $this->responseSuccess('Imagen guardada correctamente', ['redirect' => url()->previous()]);
            }

            if($request->has('video') && $request->type == Gallery::VIDEO){
                $gallery->type = Gallery::VIDEO;
                $gallery->name = $request->video;
                $gallery->image = $request->video;
                $gallery->save();
                DB::commit();
                return $this->responseSuccess('Video guardado correctamente', ['redirect' => url()->previous()]);
            }
            return $this->responseError('Contenido requerido', ['redirect' => url()->previous()]);
        }catch (\Exception $e){
            DB::rollBack();
            Log::error($e->getMessage());
            return $this->responseError('Ocurrió un error, inténtelo más tarde', ['redirect' => route('admin.project.index')]);
        }

    }

    public function order(Request $request)
    {
        try{
            $gallery1 = Gallery::find($request->start_id);
            $gallery2 = Gallery::find($request->end_id);
            $start = $gallery1->order;
            $end = $gallery2->order;
            $gallery1->order = $end;
            $gallery2->order = $start;
            $gallery1->save();
            $gallery2->save();
            return $this->responseSuccess('Ordenado correctamente', ['redirect' => url()->previous()]);

        }catch (\Exception $e){
            Log::error($e->getMessage());
            return $this->responseError('Ocurrió un error, intentelo más tarde', ['redirect' => '']);
        }
    }

    public function destroy($id)
    {
        try{
            $gallery = Gallery::find($id);
            $gallery->delete();
            return $this->responseSuccess('Eliminado correctamente', ['redirect' => url()->previous()]);
        }catch (\Exception $e){
            Log::error($e->getMessage());
            return $this->responseError('Ocurrió un error, intentelo más tarde', ['redirect' => '']);
        }
    }
}

resources/views/admin/modules/gallery/index.blade.php
@extends('admin.layouts.base')
@section('bodyId')id="gallery" @endsection
@section('content')
<section class="wrapper">
    <!-- page start-->
    <div class="row">
        <div class="col-12">
            <h3 class="title d-flex justify-content-between align-items-center">
                Gallería - Cliente: {{ $project->client }}
            </h3>
        </div>
    </div>
    {!! Form::open(['route' => ['admin.gallery.store', $project->id], 'files' => true, 'method' => 'POST']) !!}
    <div class="row">
        <div class="col-9">
            <div class="card">
                <header class="card-header d-flex flex-row">
                    Galería de fotos (dimensiones 1170 x 658 px)
                </header>
                <div class="card-body">
                    <div class="ml-0">
                    <label class="col-md-4 p-0 control-label" for="radios">Seleccione tipo de contenido</label>
                    <div class="col-md-4 p-0">
                        <label class="radio-inline" for="radio-image">
                            <input type="radio" name="type" id="radio-image" value="image" checked="checked">
                            Imagen
                        </label>
                        <label class="radio-inline" for="radio-video">
                            <input type="radio" name="type" id="radio-video" value="video">
                            Video
                        </label>
                    </div>
                    </div>
                    <div id="div-images">
                        @component('admin.partials.upload-image', ['width' => 570, 'height' => 300])
                            @slot('edit') gallery @endslot
                        @endcomponent
                    </div>
                    <div id="div-videos" style="display: none">
                        <div class="col-12 p-0">
                            <div class="form-group">
                                {!! Field::text('video', null, ['label' => '', 'placeholder' => 'https://www.youtube.com/watch?v=xTI8U8KBGQo']) !!}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <br>
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered" id="table-gallery">
                        <tbody>
                        @foreach($galleries as $gallery)
                        <tr id="{{ $gallery->id }}">
                            <td class="text-center index">{{ $loop->iteration }}</td>
                            <td class="text-center">
                                @if($gallery->type == \App\Gallery::IMAGE)
                                    <img src="{{ $gallery->getPathImage(100, 56) }}" width="100px">
                                @else
                                    <img src="{{ asset('img/youtube-icon.png') }}" width="50px" >
                                @endif
                            </td>
                            <td><a href="{{ $gallery->getPathImage(1170, 658) }}" target="_blank">{{ $gallery->getPathImage(1170, 658) }}</a></td>
                            <td class="text-center">
                                <a href="javascript:void(0)" class="icon-delete delete-image" data-target="#delete" data-toggle="modal"
                                   data-action="{{ route('admin.gallery.destroy', $gallery->id) }}"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="action d-flex flex-row">
                <button type="submit" class="button dark active">Guardar</button>
                <a href="{{ route('admin.project.index') }}" class="button red ml-2">Cancelar</a>
            </div>
        </div>
    </div>
    {!! Form::close() !!}
</section>
@include('admin.modals.loader')
@include('admin.modals.cropper-image')
@include('admin.modals.delete', [
   'title' => 'Eliminar Imagen',
   'message' => 'Esta seguro que desea eliminar esta imagen',
])
@endsection
@push('scripts')
    <script>
        $('.delete-image').on('click', function () {
            $('#form-delete').attr('action', $(this).data('action'));
            $('#delete').modal('show')
        });

        $('input[type=radio][name=type]').change(function() {
            if (this.value === 'image') {
                $('#div-images').show();
                $('#div-videos').hide();
            }
            else if (this.value === 'video') {
                $('#div-images').hide();
                $('#div-videos').show();
            }
        });
    </script>
@endpush