routes/admin.php
<?php
Route::namespace('Admin')->name('admin.')->group(function () {
//General
    Route::get('home', 'SettingController@home')->name('home.index');
    Route::get('agency', 'SettingController@agency')->name('agency.index');
    Route::post('store', 'SettingController@store')->name('setting.store');
    Route::get('contact', 'SettingController@contact')->name('contact.index');
//Category
    Route::resource('category', 'CategoryController');
//Message
    Route::resource('message', 'MessageController');
//Gallery
    Route::post('gallery/order', 'GalleryController@order');
    Route::post('gallery/{project}/store', 'GalleryController@store')->name('gallery.store');
    Route::get('gallery/{project}/create', 'GalleryController@create')->name('gallery.create');
    Route::delete('gallery/{id}/delete', 'GalleryController@destroy')->name('gallery.destroy');
//Project
    Route::resource('project', 'ProjectController');
//Client
    Route::post('client/order-client', 'ClientController@order');
    Route::resource('client', 'ClientController');
//Logs
    //Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

//Auth
/*Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});*/
Auth::routes();

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', function (){
    return redirect()->route('login');
});


Route::namespace('Web')->group(function (){
    Route::get('gracias', 'HomeController@thanks')->name('thanks');
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('nosotros', 'HomeController@agency')->name('us');
    Route::get('contacto', 'HomeController@contact')->name('contact');
    Route::get('portafolio/{slug?}', 'HomeController@project')->name('portfolio');
    Route::get('/{slug}', 'HomeController@detail')->name('portfolio-detail');
    Route::post('save-contact', 'HomeController@saveContact')->name('save-contact');
});
Route::view('/404', 'errors.404');
Route::view('/500', 'errors.500');
Route::view('/503', 'errors.503');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug', 'featured'];

    public function projects()
    {
        return $this->hasMany(Project::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('admin.modules.category.index', compact('categories'));
    }

    public function store(Request $request)
    {
        try{
            $count_featured = Category::whereFeatured(true)->count();
            if(isset($request->featured) && $count_featured == 4){
                return $this->responseError('Solo puede destacar hasta 4 categorías');
            }
            Category::updateOrCreate(['id' => $request->id], [
                    'name' => $request->name,
                    'featured' => isset($request->featured),
                    'slug' => str_replace(' ', '-', strtolower($request->name))
                ]);
            return $this->responseSuccess('Guardado correctamente', ['redirect' => route('admin.category.index')]);
        }catch (\Exception $e){
            Log::error($e->getMessage());
            return $this->responseError('Ocurrió un error, inténtelo más tarde', ['redirect' => route('admin.category.index')]);
        }

    }

    public function destroy(Category $category)
    {
        try{
            $category->delete();
            return $this->responseSuccess('Eliminado correctamente', ['redirect' => route('admin.category.index')]);
        }catch (\Exception $e){
            Log::error($e->getMessage());
            return $this->responseError('No se puede eliminar, cuenta con trabajos asignados', ['redirect' => route('admin.category.index')]);
        }
    }
}

resources/views/admin/modules/category/index.blade.php
@extends('admin.layouts.base')
@section('bodyId')id="category" @endsection
@section('content')
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-12">
                <h3 class="title d-flex justify-content-between align-items-center">
                    Portafolio - Categorías
                    <button type="button" class="button dark" data-toggle="modal" data-target="#create">
                        Agregar nuevo
                    </button>
                </h3>
            </div>
        </div>
        @include('admin.partials.alerts')
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th class="text-center w60">Orden</th>
                                <th>Nombre de categía</th>
                                <th>Trabajos asignados</th>
                                <th>Principal</th>
                                <th>F. de creación</th>
                                <th class="text-center w120">Acción</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr data-name="{{ $category->name }}" data-id="{{ $category->id }}" data-checked="{{ $category->featured }}">
                                    <td class="text-center">{{ $loop->iteration }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->projects->count() }}</td>
                                    <td>{{ $category->featured ? 'Si' : 'No' }}</td>
                                    <td>{{ $category->created_at }}</td>
                                    <td class="text-center d-flex justify-content-around">
                                        <a href="javascript:void(0)" class="icon-edit edit-category"><i class="material-icons">edit</i></a>
                                        <a href="javascript:void(0)" class="icon-delete delete-category" data-toggle="modal" data-action="{{ route('admin.category.destroy', $category->id) }}"
                                           data-target="#delete"><i class="material-icons">delete</i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @include('admin.modules.category.modal.create')
    @include('admin.modules.category.modal.edit')
    @include('admin.modals.loader')
    @include('admin.modals.delete', [
        'title' => 'Eliminar Categoría',
        'message' => 'Esta seguro que desea eliminar esta categoria',
    ])
@endsection
@push('scripts')
    <script>
        $('.delete-category').on('click', function () {
            $('#form-delete').attr('action', $(this).data('action'));
            $('#delete').modal('show')
        });
        $('.edit-category').on('click', function () {
            console.log($(this).parent().parent().data('name'));
            $('#category_name').val($(this).parent().parent().data('name'));
            $('#category_id').val($(this).parent().parent().data('id'));
            $('input[name=featured]').prop('checked', $(this).parent().parent().data('checked'));
            $('#modal-edit').modal();
        })
    </script>
@endpush