routes/admin.php
<?php
Route::namespace('Admin')->name('admin.')->group(function () {
//General
    Route::get('home', 'SettingController@home')->name('home.index');
    Route::get('agency', 'SettingController@agency')->name('agency.index');
    Route::post('store', 'SettingController@store')->name('setting.store');
    Route::get('contact', 'SettingController@contact')->name('contact.index');
//Category
    Route::resource('category', 'CategoryController');
//Message
    Route::resource('message', 'MessageController');
//Gallery
    Route::post('gallery/order', 'GalleryController@order');
    Route::post('gallery/{project}/store', 'GalleryController@store')->name('gallery.store');
    Route::get('gallery/{project}/create', 'GalleryController@create')->name('gallery.create');
    Route::delete('gallery/{id}/delete', 'GalleryController@destroy')->name('gallery.destroy');
//Project
    Route::resource('project', 'ProjectController');
//Client
    Route::post('client/order-client', 'ClientController@order');
    Route::resource('client', 'ClientController');
//Logs
    //Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

//Auth
/*Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});*/
Auth::routes();

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', function (){
    return redirect()->route('login');
});


Route::namespace('Web')->group(function (){
    Route::get('gracias', 'HomeController@thanks')->name('thanks');
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('nosotros', 'HomeController@agency')->name('us');
    Route::get('contacto', 'HomeController@contact')->name('contact');
    Route::get('portafolio/{slug?}', 'HomeController@project')->name('portfolio');
    Route::get('/{slug}', 'HomeController@detail')->name('portfolio-detail');
    Route::post('save-contact', 'HomeController@saveContact')->name('save-contact');
});
Route::view('/404', 'errors.404');
Route::view('/500', 'errors.500');
Route::view('/503', 'errors.503');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['name', 'category_id', 'client', 'campaign', 'implementation', 'year', 'outstanding',
        'place', 'description', 'cover_image', 'seo', 'slug'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getPathCoverImage($width, $height, $format = 'png')
    {
        return isset($this->cover_image) ?
            ( strpos($this->cover_image, 'https') !== false ?
                $this->cover_image : config('services.whiz.images.path') . '/' . $this->cover_image . '/' . $format . '/' . $width . '/' . $height ) : null;
    }

    public function gallery()
    {
        return $this->hasMany(Gallery::class);
    }
}

app/Http/Controllers/Admin/ProjectController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Gallery;
use App\Http\Requests\Project\StoreRequest;
use App\Http\Requests\Project\UpdateRequest;
use App\Project;
use App\Http\Controllers\Controller;
use App\Services\API\ApiWhiz;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ProjectController extends Controller
{
    protected  $apiWhiz;
    public function __construct(ApiWhiz $apiWhiz)
    {
        $this->apiWhiz = $apiWhiz;
    }

    public function index(){

        $projects = Project::orderBy('id', 'desc')->get();
        return view('admin.modules.project.index', compact('projects'));
    }

    public function create()
    {
        $categories = Category::pluck('name', 'id')->toArray();
        return view('admin.modules.project.create', compact('categories'));
    }

    public function store(StoreRequest $request)
    {
        try{
            DB::beginTransaction();
            $data = $request->except('_token');
            $data['outstanding'] = isset($request->outstanding);
            $data['slug'] = $this->createSlug($request);
            $project = Project::create($data);
            if($request->has('cover_image')){
                $multipart[] = ['name' => 'image[]', 'contents' => fopen($request->file('cover_image')->getRealPath(), 'r')];
                $dataImage = ['table_name' => 'projects', 'table_key' => $project->id];
                $responseImage = $this->apiWhiz->storeImage($dataImage, $multipart);
                if ($responseImage->response->status) {
                    $path = $responseImage->response->data[0]->uuid ?? null;
                    $project->cover_image = $path;
                    $project->save();
                }
            }
            DB::commit();
            return $this->responseSuccess('Información guardada correctamente', ['redirect' => route('admin.project.index')]);
        }catch (\Exception $e){
            DB::rollBack();
            Log::error($e->getMessage());
            return $this->responseError('Ocurrió un error, inténtelo más tarde', ['redirect' => route('admin.project.index')]);
        }

    }

    private function createSlug($request)
    {
        $slug = str_replace(' ', '-', strtolower($request->client)) . '-' . str_replace(' ', '-', strtolower($request->campaign)) .
            '-' . $request->year;
        return strtolower($slug);
    }

    public function edit(Project $project)
    {
        $categories = Category::pluck('name', 'id')->toArray();
        return view('admin.modules.project.edit', compact('project', 'categories'));
    }

    public function update(UpdateRequest $request, Project $project)
    {
        try{
            $data = $request->except('_token');
            $data['outstanding'] = isset($request->outstanding);
            $project->update($data);
            if($request->has('cover_image')){
                $multipart[] = ['name' => 'image[]', 'contents' => fopen($request->file('cover_image')->getRealPath(), 'r')];
                $dataImage = ['table_name' => 'projects', 'table_key' => $project->id];
                $responseImage = $this->apiWhiz->storeImage($dataImage, $multipart);
                if ($responseImage->response->status) {
                    $path = $responseImage->response->data[0]->uuid ?? null;
                    $project->cover_image = $path;
                    $project->save();
                }
            }
            return $this->responseSuccess('Información guardada correctamente', ['redirect' => route('admin.project.index')]);
        }catch (\Exception $e){
            Log::error($e->getMessage());
            return $this->responseError('Ocurrió un error, inténtelo más tarde', ['redirect' => route('admin.project.index')]);
        }
    }

    public function destroy(Project $project)
    {
        try{
            DB::beginTransaction();
            Gallery::where('project_id', $project->id)->delete();
            $project->delete();
            DB::commit();
            return $this->responseSuccess('Eliminado correctamente', ['redirect' => route('admin.project.index')]);
        }catch (\Exception $e){
            DB::rollBack();
            Log::error($e->getMessage());
            return $this->responseError('Ocurrió un error, inténtelo más tarde', ['redirect' => route('admin.project.index')]);
        }
    }
}

resources/views/admin/modules/project/create.blade.php
@extends('admin.layouts.base')
@section('bodyId')id="project" @endsection
@section('content')
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-12">
                <h3 class="title d-flex justify-content-between align-items-center">
                    Nuevo - Proyecto
                </h3>
            </div>
        </div>
        {!! Form::open(['route' => 'admin.project.store', 'files' => true]) !!}
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <header class="card-header d-flex justify-content-between">
                        Información principal
                        <div class="">
                            <input type="checkbox" name="outstanding"> Destacado
                        </div>

                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('client', $project->client ?? null, ['label' => 'Cliente', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('campaign', $project->campaign ?? null, ['label' => 'Campaña', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('implementation', $project->implementation ?? null, ['label' => 'Implementación', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::select('category_id', $categories, null, ['label' => 'Categoría', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('year', $project->year ?? null, ['label' => 'Año', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('place', $project->place ?? null, ['label' => 'Lugar', 'placeholder' => '']) !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="card">
                    <header class="card-header">
                        Descripción
                    </header>
                    <div class="card-body">
                        <textarea class="summernote" name="description"></textarea>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="action d-flex justify-content-between">
                    <button type="submit" class="button dark active">Guardar</button>
                    <a href="{{ route('admin.project.index') }}" class="button red">Cancelar</a>
                </div>
                <br>
                <div class="card">
                    <header class="card-header">
                        Imagen de Portada
                    </header>
                    <div class="card-body">
                        La imagen debe medir al menos 437 x 270 px
                        @component('admin.partials.upload-image', ['width' => 437, 'height' => 270])
                            @slot('edit') cover_image @endslot
                        @endcomponent
                    </div>
                </div>
                <br>
                <div class="card">
                    <header class="card-header">
                        Etiqueta SEO (separe por comas)
                    </header>
                    <div class="card-body">
                        <div class="form-group">
                            <input class="form-control" id="seo" name="seo" type="text">
                        </div>
                    </div>
                </div>
            </div>

            <br>
        </div>
        {!! Form::close() !!}
    </section>
    @include('admin.modals.loader')
    @include('admin.modals.cropper-image')
@endsection

resources/views/admin/modules/project/edit.blade.php
@extends('admin.layouts.base')
@section('bodyId')id="project" @endsection
@section('content')
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-12">
                <h3 class="title d-flex justify-content-between align-items-center">
                    Nuevo - Proyecto
                </h3>
            </div>
        </div>
        {!! Form::open(['route' => ['admin.project.update', $project->id], 'files' => true, 'method' => 'PUT']) !!}
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <header class="card-header d-flex justify-content-between">
                        Información principal
                        <div class="">
                            <input type="checkbox" name="outstanding" value="1" {{ $project->outstanding ? 'checked' : '' }}> Destacado
                        </div>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('client', $project->client ?? null, ['label' => 'Cliente', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('campaign', $project->campaign ?? null, ['label' => 'Campaña', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('implementation', $project->implementation ?? null, ['label' => 'Implementación', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::select('category_id', $categories, $project->category_id, ['label' => 'Categoría', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('year', $project->year ?? null, ['label' => 'Año', 'placeholder' => '']) !!}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    {!! Field::text('place', $project->place ?? null, ['label' => 'Lugar', 'placeholder' => '']) !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="card">
                    <header class="card-header">
                        Descripción
                    </header>
                    <div class="card-body">
                        <textarea class="summernote" name="description">{{ $project->description }}</textarea>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="action d-flex justify-content-between">
                    <button type="submit" class="button dark active">Guardar</button>
                    <a href="{{ route('admin.project.index') }}" class="button red">Cancelar</a>
                </div>
                <br>
                <div class="card">
                    <header class="card-header">
                        Imagen de Portada
                    </header>
                    <div class="card-body">
                        La imagen debe medir al menos 599 x 476 px
                        @component('admin.partials.upload-image', [
                            'path' => $project->path_cover_image ?? '',
                            'width' => 350,
                            'height' => 280
                            ])
                            @slot('edit') cover_image @endslot
                        @endcomponent
                    </div>
                </div>
                <br>
                <div class="card">
                    <header class="card-header">
                        Etiqueta SEO (separe por comas)
                    </header>
                    <div class="card-body">
                        <div class="form-group">
                            <input class="form-control" id="seo" name="seo" type="text" value="{{ $project->seo }}">
                        </div>
                    </div>
                </div>
            </div>

            <br>
        </div>
        {!! Form::close() !!}
    </section>
    @include('admin.modals.loader')
    @include('admin.modals.cropper-image')
@endsection

resources/views/admin/modules/project/index.blade.php
@extends('admin.layouts.base')
@section('bodyId')id="project" @endsection
@section('content')
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-12">
                <h3 class="title d-flex justify-content-between align-items-center">
                    Portafolio - Proyectos
                    <a href="{{ route('admin.project.create') }}" class="button dark">
                        Crear nuevo
                    </a>
                </h3>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <table id="table-projects" class="table table-bordered">
                            <thead>
                            <tr>
                                <th class="text-center w60">Orden</th>
                                <th>Cliente</th>
                                <th>Campaña</th>
                                <th>Categoría</th>
                                <th class="text-center w120">Acción</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($projects as $project)
                                <tr>
                                    <td class="text-center">{{ $loop->iteration }}</td>
                                    <td>{{ $project->client }}</td>
                                    <td>{{ $project->campaign }}</td>
                                    <td>{{ $project->category->name }}</td>
                                    <td class="text-center d-flex justify-content-around">
                                        <a href="{{ route('admin.project.edit', $project->id) }}" class="icon-edit">
                                            <i class="material-icons">edit</i></a>
                                        <a href="{{ route('admin.gallery.create', $project->id) }}" class="icon-edit">
                                            <i class="material-icons">image</i></a>
                                        <a href="javascript:void(0)" class="icon-delete delete-project" data-toggle="modal"
                                           data-target="#delete" data-action="{{ route('admin.project.destroy', $project->id) }}"><i class="material-icons">delete</i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @include('admin.modules.category.modal.create')
    @include('admin.modules.category.modal.edit')
    @include('admin.modals.delete', [
       'title' => 'Eliminar Proyecto',
       'message' => 'Esta seguro que desea eliminar esta proyecto',
   ])
@endsection
@push('scripts')
    <script>
        $('.delete-project').on('click', function () {
            $('#form-delete').attr('action', $(this).data('action'));
            $('#delete').modal('show')
        });

        $('#table-projects').DataTable({
            language: {'url': 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json'},
            searching: false,
        });
    </script>
@endpush