routes/admin.php
<?php
Route::namespace('Admin')->name('admin.')->group(function () {
//General
    Route::get('home', 'SettingController@home')->name('home.index');
    Route::get('agency', 'SettingController@agency')->name('agency.index');
    Route::post('store', 'SettingController@store')->name('setting.store');
    Route::get('contact', 'SettingController@contact')->name('contact.index');
//Category
    Route::resource('category', 'CategoryController');
//Message
    Route::resource('message', 'MessageController');
//Gallery
    Route::post('gallery/order', 'GalleryController@order');
    Route::post('gallery/{project}/store', 'GalleryController@store')->name('gallery.store');
    Route::get('gallery/{project}/create', 'GalleryController@create')->name('gallery.create');
    Route::delete('gallery/{id}/delete', 'GalleryController@destroy')->name('gallery.destroy');
//Project
    Route::resource('project', 'ProjectController');
//Client
    Route::post('client/order-client', 'ClientController@order');
    Route::resource('client', 'ClientController');
//Logs
    //Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

//Auth
/*Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});*/
Auth::routes();

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', function (){
    return redirect()->route('login');
});


Route::namespace('Web')->group(function (){
    Route::get('gracias', 'HomeController@thanks')->name('thanks');
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('nosotros', 'HomeController@agency')->name('us');
    Route::get('contacto', 'HomeController@contact')->name('contact');
    Route::get('portafolio/{slug?}', 'HomeController@project')->name('portfolio');
    Route::get('/{slug}', 'HomeController@detail')->name('portfolio-detail');
    Route::post('save-contact', 'HomeController@saveContact')->name('save-contact');
});
Route::view('/404', 'errors.404');
Route::view('/500', 'errors.500');
Route::view('/503', 'errors.503');

resources/views/admin/partials/alerts.blade.php
@if(session()->has('success'))
<div class="alert alert-success" role="alert">
    {{ session('success') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
@if(session()->has('error'))
<div class="alert alert-danger" role="alert">
    {{ session('error') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

resources/views/admin/partials/aside.blade.php
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
            <li class="nav-only {{ Route::is('admin.home.index') ? 'active' : ''}}">
                <a class="" href="{{ route('admin.home.index') }}">Inicio</a>
            </li>
            <li class="sub-menu">
                <a href="javascript:void(0)" class="{{ Route::is('admin.home.job') ? 'active' : ''}}">
                    <span>Portafolio</span>
                </a>
                <ul class="sub">
                    <li class="{{ Route::is('admin.category.index') ? 'active' : ''}}">
                        <a href="{{ route('admin.category.index') }}">Categorías</a>
                    </li>
                    <li class="{{ Route::is('admin.project.index') ? 'active' : ''}}">
                        <a href="{{ route('admin.project.index') }}">Trabajos</a>
                    </li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href="javascript:void(0)" class="">
                    <span>Nosotros</span>
                </a>
                <ul class="sub">
                    <li class="{{ Route::is('admin.agency.index') ? 'active' : ''}}">
                        <a href="{{ route('admin.agency.index') }}">La Agencia</a>
                    </li>
                    <li class="{{ Route::is('admin.client.index') ? 'active' : ''}}">
                        <a href="{{ route('admin.client.index') }}">Clientes</a>
                    </li>
                </ul>
            </li>
            <li class="nav-only {{ Route::is('admin.contact.*') ? 'active': '' }}">
                <a href="{{ route('admin.contact.index') }}">Contacto</a>
            </li>
            <li class="nav-only {{ Route::is('admin.message.*') ? 'active': '' }}">
                <a href="{{ route('admin.message.index') }}">Suscriptores</a>
            </li>
        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->

resources/views/admin/partials/footer.blade.php
<!--footer start-->
<footer class="site-footer">
    <div class="text-center">
        La Protectora | Todos los derechos reservados 2019 - <a href="javascript:void(0)" class="company">Powered by Whiz</a>
        <a href="#" class="go-top"><i class="material-icons">keyboard_arrow_up</i></a>
    </div>
</footer>
<!--footer end-->

resources/views/admin/partials/header.blade.php
<!--header start-->
<header class="header">
    <div class="brand">
        <!--logo start-->
        <a href="javascript:void(0)" class="logo">
            <img src="{{ url('img/logo.png') }}" alt="" width="160px" height="45px">
        </a>
        <!--logo end-->
    </div>
    <div class="top-nav">
        <a href="{{ route('logout') }}" class="button"
           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            Cerrar sesión
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </div>
</header>
<!--header end-->

resources/views/admin/partials/heading.blade.php
<div class="row">
    <div class="col-sm-12">
        <div class="panel">
            <header class="panel-heading">{{ $heading }}</header>
        </div>
    </div>
</div>

resources/views/admin/partials/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: skep
 * Date: 2019-07-16
 * Time: 15:25
 */

resources/views/admin/partials/upload-image.blade.php
<div class="fileupload fileupload-new d-flex" data-provides="fileupload">

    <div class="row">
        @isset($path)
        <div class="fileupload-new thumbnail btn-file before-show col-12"
             style="background-color: #EFEFEF">

                <img class="img-fluid" src="{{ $path }}"/>
            {{--@else
                <img src="{{ asset('img/default.png') }}" alt="" style="width: 250px"/>
            @endif--}}
            <input type="file" class="default" data-input="{{ $edit }}"/>
        </div>
        @endif
        <div class="fileupload-preview fileupload-exists thumbnail {{ $edit }} col-12"
             style="width: {{ $width }}px; height: {{ $height }}px; max-width: {{ $width }}px; max-height: {{ $height }}px; line-height: 20px;">
        </div>
        <div class="col-12">
        <span class="btn btn-white btn-file p-0">
            <span class="fileupload-new button" style="width: 100%">Seleccionar imagen</span>
            <span class="fileupload-exists button">Cambiar imagen</span>
            <input type="file" class="default"/>
        </span>
            <div class="d-flex mt-1">
                <a href="#" class="btn btn-danger fileupload-exists m-0" data-dismiss="fileupload">
                    <i class="fa fa-trash"></i> Eliminar
                </a>
                <button id="{{ $edit }}" type="button" class="btn btn-warning fileupload-exists mt-0 ml-2"
                        data-toggle="modal" data-input="{{ $edit }}" data-target="#cropper_modal">
                    <i class="fa fa-edit"></i>Editar
                </button>
            </div>
        </div>
    </div>

</div>

resources/views/admin/partials/upload_image_multiple.blade.php
<form action="" id="{{ empty($id)?'fileupload':$id }}">
    <div class="row">
        <div class="col-md-12">
            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            <div class="row fileupload-buttonbar">
                <div class="col-lg-12">
                    <!-- The fileinput-button span is used to style the file input field as button -->
                    <span class="btn btn-success fileinput-button">
                        <i class="glyphicon glyphicon-plus"></i>
                        <span>Agregar archivos...</span>
                        <input type="file" name="gallery[]" multiple>
                    </span>
                    <button type="submit" class="btn btn-primary start">
                        <i class="glyphicon glyphicon-upload"></i>
                        <span>Subir</span>
                    </button>
                    <button type="reset" class="btn btn-warning cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        <span>Cancelar</span>
                    </button>
                    <button type="button" class="btn btn-danger delete">
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Eliminar</span>
                    </button>
                    <input type="checkbox" class="toggle">
                    <!-- The global file processing state -->
                    <span class="fileupload-process"></span>
                </div>
                <!-- The global progress state -->
                <div class="col-lg-12 fileupload-progress fade">
                    <!-- The global progress bar -->
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0"
                         aria-valuemax="100">
                        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                    </div>
                    <!-- The extended global progress state -->
                    <div class="progress-extended">&nbsp</div>
                </div>
            </div>
            <!-- The table listing the files available for upload/download -->
            <table role="presentation" class="table table-striped">
                <tbody class="files">
                @foreach($gallery as $file)
                    @if(file_exists($file->path))
                        <tr class="template-download fade in">
                            <td>
                                <span class="preview">
                                    @if ($file->thumbnail && $is_image)
                                        <a href="{{ url($file->path) }}" title="" download="" data-gallery>
                                            <img src="{{ $file->thumbnail }}"></a>
                                    @endif
                                </span>
                            </td>
                            <td style="vertical-align: middle">
                                <p class="name">
                                    <a href="{{ url($file->path) }}" title="{{ $file->name }}"
                                       download="{{ $file->name }}" data-gallery> {{ $file->name }}</a>
                                </p>
                            </td>
                            <td style="vertical-align: middle">
                                <p class="name">
                                    <input type="text" class="form-control" placeholder="Link" name="description"
                                           value="{{ $file->description }}">
                                </p>
                            </td>
                            <td style="vertical-align: middle"><span class="size">{{ $file->size }}</span></td>
                            <td style="vertical-align: middle; text-align: right">
                                <button type="button" class="btn btn-warning edit"
                                        data-url="{{ route('gallery.update', ['id'=> $file->id]) }}">
                                    <i class="glyphicon glyphicon-pencil"></i><span>Editar</span>
                                </button>
                                <button class="btn btn-danger delete" data-type="DELETE"
                                        data-url="{{ url('/admin/gallery/'.$type.'/'.$file->id) }}">
                                    <i class="glyphicon glyphicon-trash"></i><span>Eliminar</span>
                                </button>
                                <input type="checkbox" name="delete" value="1" class="toggle">
                            </td>
                        </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</form>